# Generated by Django 3.0.3 on 2020-03-14 13:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_sso', '0002_sessiontoken_last_used_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='a primary key of a model meta', primary_key=True, serialize=False)),
                ('jti', models.TextField(editable=False, verbose_name='a token jti claim value')),
                ('token', models.TextField(editable=False, verbose_name='a token representation')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Session token',
                'verbose_name_plural': 'Session tokens',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SessionToken',
        ),
        migrations.AddIndex(
            model_name='tokenmeta',
            index=models.Index(fields=['ip_address'], name='rest_framew_ip_addr_6a4c4c_idx'),
        ),
    ]
